#!/usr/bin/env bash
# This script installs a load balancer haproxy and configures it

sudo apt-get -y install --no-install-recommends software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-2.6
sudo apt-get -y update
sudo apt-get -y install haproxy
load_balancer="\nfrontend http\n
\tbind *:80
\tmode http
\tdefault_backend load_b
backend load_b\n
\tbalance roundrobin
\tserver web-01 52.2.208.130 check
\tserver web-02 100.25.146.78 check
"
echo -e "ENABLED=1\n" | sudo tee -a /etc/default/haproxy
echo -e "$load_balancer" | sudo tee -a /etc/haproxy/haproxy.cfg

service haproxy restart
